Repository wexond/browser-base, pull requests merged in 2020-06, with the labels that each got.

#480 refactor: bookmarks storage
  .eslintrc.js
  .gitignore
  package.json
  src/browser/application.ts
  src/browser/browser-contexts.ts
  src/browser/models/settings.ts
  src/common/utils/date.ts
  src/common/utils/files.ts
  src/common/utils/string.ts
  src/interfaces/bookmark.ts
  src/interfaces/storage.ts
  src/preloads/models/database.ts
  src/preloads/utils/autofill.ts
  src/renderer/extensions/injector.ts
  src/storage/constants/config.ts
  src/storage/constants/index.ts
  src/storage/index.ts
  src/storage/interfaces/bookmarks.ts
  src/storage/interfaces/index.ts
  src/storage/loaders/communication.ts
  src/storage/loaders/db.ts
  src/storage/loaders/index.ts
  src/storage/services/bookmarks.ts
  src/storage/utils/index.ts
  src/storage/utils/schema.ts
  src/storage/utils/string.ts
  src/utils/files.ts
  src/utils/string.ts
  static/storage/bookmarks.json
  static/storage/schema.sql
  webpack.config.base.js
  webpack.config.js
  yarn.lock
Labels: enhancement, performance

#488 feat: history storage
  src/browser/extensions/api/history.ts
  src/browser/extensions/index.ts
  src/browser/services/history.ts
  src/browser/services/storage.ts
  src/common/extensions/api/_api_features.json
  src/common/extensions/api/history.json
  src/common/services/history.ts
  src/common/utils/date.ts
  src/common/utils/files.ts
  src/interfaces/history.ts
  src/interfaces/index.ts
  src/interfaces/storage.ts
  src/storage/constants/config.ts
  src/storage/index.ts
  src/storage/interfaces/history.ts
  src/storage/interfaces/index.ts
  src/storage/loaders/communication.ts
  src/storage/loaders/db.ts
  src/storage/loaders/index.ts
  src/storage/services/bookmarks.ts
  src/storage/services/communication.ts
  src/storage/services/db.ts
  src/storage/services/history.ts
  src/storage/utils/date.ts
  src/storage/utils/index.ts
  src/storage/utils/schema.ts
  static/storage/history.sql
  static/storage/schema.sql
Labels: chrome-extensions, enhancement

#498 feat: add favicon2 protocol
  package.json
  src/browser/protocols/wexond.ts
  src/interfaces/favicon.ts
  src/storage/services/db.ts
  src/storage/services/favicons.ts
  yarn.lock
Labels: enhancement

#505 fix: copying images
  src/main/menus/view.ts
Labels: target/5-x-y

#504 fix: moving pinned tabs
  src/renderer/views/app/store/tabs.ts
Labels: target/5-x-y

#503 fix: closing windows
  src/main/windows/app.ts
Labels: target/5-x-y

#502 chore: upgrade dependencies
  package.json
  yarn.lock
Labels: target/5-x-y

#508 feat: add history private
  src/browser/extensions/api/history-private.ts
  src/browser/extensions/index.ts
  src/browser/services/history.ts
  src/common/extensions/api/_api_features.json
  src/common/extensions/api/history_private.idl
  src/interfaces/history-private.ts
  src/interfaces/storage.ts
  src/storage/services/history.ts
Labels: enhancement
